apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: f8d0utwpj-java-springboot-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/f8d0utwpj-java-springboot-gitops